version: '3'

services: 
  app:
    container_name: app
    build:
      context: ./node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s node index.ts 
      - ./node:/opt/app/node

    networks: 
      - node_network
    tty: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql_volumes:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node_network

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    entrypoint: dockerize -wait http://app:3000 -timeout 40s nginx -g 'daemon off;'
    tty: true
    ports:
      - "8080:80"
    networks:
      - node_network
    depends_on:
      - app


networks:
  node_network:
    driver: bridge